name: Baysan Continuous Delivery

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Stop Old Docker Compose Environment
      run: docker compose down

    - name: Build & Run Docker Compose Environment
      run: docker compose up -d --build

    - name: Remove Unused Docker Compose Environment
      run: |
        docker container prune -f
        docker image prune -f

    
